spring:
  config:
    import: optional:file:.env[.properties]
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      password:
  sql:
    init:
      mode: always
      schema-locations: "classpath:db/schema.sql"
      data-locations: "classpath:db/data.sql"
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_NAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
jwt:
  secret: ${JWT_TOKEN}

gemini:
  api:
    key: ${AI_KEY}
