spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/<DB?>
    username: <PostgreSQL ???>
    password: <????>
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update